# Skip rust checks in CI, they are run separately
ci:
  autofix_commit_msg: "chore(format): auto fixes from pre-commit.ci"
  skip:
    - fmt
    - cargo-check
    - clippy

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: pretty-format-json
        args: ["--autofix", "--indent=2"]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: ["--all-targets", "--all-features", "--workspace", "--fix", "--allow-dirty"]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.6
    hooks:
      - id: uv-lock
        alias: generate-pyo3-stubs
        name: generate PyO3 stubs
        entry: uvx maturin generate-stubs --features python -o python/pyasic_rs
        always_run: true
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.0
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
        additional_dependencies: [pydantic==2.12.5]
        pass_filenames: false
